INSERT INTO Student (NAME , groupnumber) VALUES ( 'John' , 1),( 'Chris' , 1), ( 'Carl', 1);
INSERT INTO Student (NAME , groupnumber) VALUES ( 'Oliver' , 2),( 'James' , 2), ( 'Lucas', 2),('Henry', 2);
INSERT INTO Student (NAME , groupnumber) VALUES ( 'Jacob' , 3),( 'Logan' , 3);
INSERT INTO Student (NAME , groupnumber) VALUES ( 'Daniel' , 4),( 'Joseph' , 4),('Paul',4);
INSERT INTO Student (NAME , groupnumber) VALUES ( 'George' , 5),( 'Andrew' , 5),('Mark',5);
INSERT INTO SUBJECT (NAME, GRADE) VALUES ( 'Art', 1 ),('Music', 1);
INSERT INTO SUBJECT (NAME, GRADE) VALUES ( 'Geography', 2),('History', 2);
INSERT INTO SUBJECT (NAME, GRADE) VALUES ( 'PE', 3),('Math', 3);
INSERT INTO SUBJECT (NAME, GRADE) VALUES ( 'Science', 4),('IT', 4);
INSERT INTO SUBJECT (NAME, GRADE) VALUES ( 'Philosophy', 5),('Sociology', 5);
INSERT INTO PAYMENTTYPE (NAME) VALUES ( 'DAILY' ),('WEEKLY'),('MONTHLY');
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'WEEKLY' WHERE s.NAME = 'John';
INSERT INTO PAYMENT(STUDENT_ID ,TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'MONTHLY' WHERE s.NAME = 'Oliver';
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'WEEKLY' WHERE s.NAME = 'Henry';
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'DAILY' WHERE s.NAME = 'James';
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'WEEKLY' WHERE s.NAME = 'Jacob';
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'DAILY' WHERE s.NAME = 'Carl';
INSERT INTO PAYMENT(STUDENT_ID, TYPE_ID) SELECT s.id , pt.id FROM STUDENT s JOIN PAYMENTTYPE pt ON pt.NAME = 'DAILY' WHERE s.NAME = 'Lucas';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 8 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'Art' WHERE s.NAME = 'Chris';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 5 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'History' WHERE s.NAME = 'Oliver';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 9 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'Geography' WHERE s.NAME = 'James';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 4 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'Math' WHERE s.NAME = 'Jacob';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 9 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'PE' WHERE s.NAME = 'Logan';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 6 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'IT' WHERE s.NAME = 'Carl';
INSERT INTO MARK(STUDENT_ID, SUBJECT_ID, MARK) SELECT s.id , subj.id, 6 FROM STUDENT s JOIN SUBJECT subj ON subj.NAME = 'Sociology' WHERE s.NAME = 'Lucas';




